### 주제 : #예외 #Exception #예외처리 #try #catch #Try-Catch문 

___

### 예외 : 

>[!note] 오류의 종류
> 프로그램을 실행하다가 보면 어떤 원인때문에 비정상적인 동작을 일으키며 프로그램이 종료되는 상황을 보신적 있으실 겁니다. 이때 우리는 프로그램이 오류가 발생했다고 합니다.
> 에러의 종류는 우리가 컴파일할때 발생할 수 있는 ==컴파일 오류==와 실행 중 발생되는 ==런타임 오류== 두 종류가 있지요.

>[!note] 런타임 오류의 종류 
> 컴파일 오류는 우리가 잡기가 쉽지만, 런타임 오류는 잡기가 까다롭습니다. 
> 자바에서는 런타임 오류를 두 종류로 보고 있습니다. 바로 **에러(Error)**와 **예외(Exception)**으로 말이죠. 

>[!note] 에러란?
> 에러는 프로그램이 코드로 복구될 수 없는 오류를 의미하고 예외는 프로그래머가 직접 예측하여 막을 수 있는 처리가능한 오류라고 보시면 됩니다. 
> 예를 들어 메모리가 부족한 경우 프로그래머가 직접 제어할 수 없으므로 이런 경우는 메모리 부족(OutOfMemoryError) 에러가 발생하고 함수 호출이 많아 스택이 쌓일 경우에는 StackOverFlowError가 발생할 수 있습니다.

>[!note] 예외의 종류
> 예외는 Compile 시 발견할 수 있는 예외와 프로그램 실행 시 발생하는 예외 두 종류가 있습니다. 
> Compile시에 발생할 수 있는 예외는 Eclipse와 같은 IDE를 쓰신다면 빨간줄로 예외를 처리하라고 욕합니다.
> 그런 예외가 발생했을때 어떤 동작을 처리해야하는지를 우리는 **예외 처리**라고 합니다.

### Try-Catch문 구조 : 

>try { 
>> // 예외 발생할 가능성이 있는 문장 
>
> } catch ( IOException e ) { 
> >// IOException 발생했을 경우, 이를 처리하기 위한 문장 적는다.  
> >// 보통 이곳에 예외 메세지를 출력하고 로그로 남김. 
>
> } catch( Exception e ) { 
>> // Exception이 발생했을 경우, 이를 처리하지 위한 문장 적는다. 
>
> } finally { 
>> // 예외 발생 여부와 관계없이 항상 수행되어야 하는 문장 적는다.
>
> }

>[!note] try 블록 :
> 이 블록에서 예외가 발생할만한 코드가 쓰여집니다. 

>[!note] catch (예외 종류) 블록 : 
> 이 부분에서 예외가 발생되었을때 처리하는 동작을 명시합니다.
> catch블록은 여러 개가 있을 수 있습니다. 
> 맨 처음 catch 블록에서 잡히지 않는 예외라면 다음 catch의 예외를 검사합니다. 이때 상속관계에 있는 예외 중 부모가 위의 catch, 그리고 그 자식 예외 클래스가 아래의 catch로 놓일 순 없습니다. 
> 예를 들어 아래와 같이말이죠.
> ```
> // 잘못된 예시
> try{
> 	//.. 중략 ..//
> } catch (Exception e){
> 	// 컴파일 오류 발생
> } catch (IOException e){
> }
>```
>
> Exception 클래스는 모든 예외의 부모이기 때문에 Exception을 IOException보다 위에서 처리할 수는 없다는 뜻입니다. 왜냐면 IOException의 catch블록은 도달할 수 없는 코드이기 때문이죠.

>[!note] finally 블록 : 
> 여기서는 예외가 발생하건 발생하지 않건 공통으로 수행되어야할 코드가 쓰여집니다.  임시 파일의 삭제 등 뒷정리 코드가 쓰입니다.

### throws : 

>[!note] 예외 던지기 : 
> 예외를 여기서 처리하지 않을테니 나를 불러다가 쓰는 녀석에게 에러 처리를 전가하겠다는 의미이며 코드를 짜는 사람이 이 선언부를 보고 어떤 예외가 발생할 수 있는지도 알게 해줍니다. 
>```
>public static void divide(int a,int b) throws ArithmeticException {
>	if(b==0) throw new ArithmeticException("0으로 나눌 수는 없다니까?"); 
>	int c=a/b;
>	System.out.println(c);
>}
>public static void main(String[] ar){
>	int a=10;
>	int b=0;
>	divide(a,b);
>}
>```
> 
>```
>public static void divide(int a,int b) throws ArithmeticException {
>	if(b==0) throw new ArithmeticException("0으로 나눌 수는 없다니까?");
>	int c=a/b;
>	System.out.println(c);
>}
>public static void main(String[] ar){
>	int a=10;
>	int b=0;
>	try {
>		divide(a,b);
>	}catch(ArithmeticException e) {
>		e.getMessage();
>		e.printStackTrace();
>	}
>}
>```

___

### 출처(참고문헌)

- [Exception](https://reakwon.tistory.com/155)
- [Try-Catch문](https://cheershennah.tistory.com/147)

___

### 연결문서

- [[자바란]]
- [[제어  구문]]
